export const THUNK_FETCHING_USERS = 'THUNK_FETCHING_USERS';
export const THUNK_FETCHING_USERS_SUCCESS = 'THUNK_FETCHING_USERS_SUCCESS';
export const THUNK_FETCHING_USERS_FAILURE = 'THUNK_FETCHING_USERS_FAILURE';
export const THUNK_SAVE_USER_SUCCESS = 'THUNK_SAVE_USER_SUCCESS';
export const THUNK_SAVE_USER_FAILURE = 'THUNK_SAVE_USER_FAILURE';

export const PROMISE_FETCH_USERS = 'FETCH_USERS';
export const PROMISE_SAVE_USER = 'SAVE_USER';

export const ASYNC_AWAIT_FETCHING_USERS = 'ASYNC_AWAIT_FETCHING_USERS';
export const ASYNC_AWAIT_FETCH_USERS_SUCCESS = 'ASYNC_AWAIT_FETCHING_USERS_SUCCESS';
export const ASYNC_AWAIT_FETCH_USERS_FAILURE = 'ASYNC_AWAIT_FETCHING_USERS_FAILURE';
export const ASYNC_AWAIT_SAVING_USERS = 'ASYNC_AWAIT_SAVING_USERS';
export const ASYNC_AWAIT_SAVE_USERS_SUCCESS = 'ASYNC_AWAIT_SAVE_USERS_SUCCESS';
export const ASYNC_AWAIT_SAVE_USERS_FAILURE = 'ASYNC_AWAIT_SAVE_USERS_FAILURE';

export const SAGA_FETCH_USERS = 'SAGA_FETCH_USERS';
export const SAGA_FETHING_USERS = 'SAGA_FETCHING_USERS';
export const SAGA_FETCH_USERS_SUCCESS = 'SAGA_FETCH_USERS_SUCCESS';
export const SAGA_FETCH_USERS_FAILURE = 'SAGA_FETCH_USERS_FAILURE';
export const SAGA_SAVE_USER = 'SAGA_SAVE_USER';
export const SAGA_SAVING_USER = 'SAGA_SAVING_USER';
export const SAGA_SAVE_USER_SUCCESS = 'SAGA_SAVE_USER_SUCCESS';
export const SAGA_SAVE_USER_FAILURE = 'SAGA_SAVE_USER_FAILURE';

export const OBSERVABLES_FETCH_USERS = 'OBSERVABLES_FETCH_USERS';
export const OBSERVABLES_FETCHING_USERS = 'OBSERVABLES_FETCHING_USERS';
export const OBSERVABLES_FETCH_USERS_SUCCESS = 'OBSERVABLES_FETCH_USERS_SUCCESS';
export const OBSERVABLES_FETCH_USERS_FAILURE = 'OBSERVABLES_FETCH_USERS_FAILURE';
export const OBSERVABLES_SAVE_USER = 'OBSERVABLES_SAVE_USER';
export const OBSERVABLES_SAVING_USER = 'OBSERVABLES_SAVING_USER';
export const OBSERVABLES_SAVE_USER_SUCCESS = 'OBSERVABLES_SAVE_USER_SUCCESS';
export const OBSERVABLES_SAVE_USER_FAILURE = 'OBSERVABLES_SAVE_USER_FAILURE';